openapi: 3.0.0
info: 
  title: OKR
  description: App to create and track OKRs
  contact:
    name: Olivier
    email: olivier.demeulder@nytimes.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: https://okr.nyt.net
tags:
  - name: objective
    description: The O in OKRs 
  - name: kr
    description: Key Result, the KR in ORKs
paths:
  '/objectives':
    get:
      tags:
        - objective
      description: Returns all objectives
      responses:
        '200':
          description: A list of objectives.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Objective'
  /objective:
    post:
      tags:
        - objective
      summary: Add a new objective to the repository
      description: ''
      operationId: addObjective
      requestBody:
        description: Objective object that needs to be added to the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Objective'
        required: true
      responses:
        '405':
          description: Invalid input
    put:
      tags:
        - objective
      summary: Update an existing objective
      description: ''
      operationId: updateObjective
      requestBody:
        description: Objective object that needs to be added to the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Objective'
        required: true
      responses:
        '400':
          description: Invalid ID supplied
        '404':
          description: Objective not found
        '405':
          description: Validation exception
  '/objective/{objectiveId}':
    get:
      tags:
        - objective
      summary: Find objective by ID
      description: Returns a single objective
      operationId: getObjectiveById
      parameters:
        - name: objectiveId
          in: path
          description: ID of objective to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Objective'
        '400':
          description: Invalid ID supplied
        '404':
          description: Objective not found
    delete:
      tags:
        - objective
      summary: Deletes an objective
      description: ''
      operationId: deleteObjective
      parameters:
        - name: api_key
          in: header
          required: false
          schema:
            type: string
        - name: objectiveId
          in: path
          description: Objective id to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '400':
          description: Invalid ID supplied
        '404':
          description: Objective not found
  /objective/{objectiveId}/krs:
    get:
      tags:
        - kr
      summary: Get key results for an objective
      operationId: getKrsById
      parameters:
        - name: objectiveId
          in: path
          required: true
          description: Objective Id for which to get KRs
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operatoin
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Kr'
        '400':
          description: Invalid ID supplied
        '404':
          description: Objective not found
  /kr:
    post:
      tags:
        - kr
      summary: Create new kr
      operationId: addKr
      requestBody:
        description: KR object that needs to be added to the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Kr'
        required: true
      responses:
        '405':
          description: Invalid input      
    put:
      tags:
        - kr
      summary: Update existing kr
      operationId: updateKr
      requestBody:
        description: KR object that needs to be added to the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Kr'
        required: true
      responses:
        '405':
          description: Invalid input
  '/kr/{krId}':
    delete:
      tags:
        - kr
      summary: Delete a Kr
      operationId: deleteKr
      parameters:
        - name: krId
          in: path
          required: true
          description: KR Id for which to get KRs
          schema:
            type: integer
            format: int64
      responses:
        '400':
          description: Invalid ID supplied
        '404':
          description: KR not found
        
components:
  schemas:
    ObjectiveStatus:
      type: string
      enum: 
        - Active
        - Achieved
        - In Progress
        - Cancelled
    KrStatus:
      type: string
      enum: 
        - Active
        - Achieved
        - In Progress
        - Cancelled
    Objective:
      type: object
      properties:
        id:
          type: integer
          format: int64
        description:
          type: string
        organization_id:
          type: integer
          format: int64
        parent_id:
          type: integer
          format: int64
        status: 
          $ref: '#/components/schemas/ObjectiveStatus'
        createdBy: 
          type: integer
    Kr:
      type: object
      properties:
        id:
          type: integer
          format: int64
        description: 
          type: string
        baseline:
          type: string
        score:
          type: integer
          minimum: 0
          maximum: 100
        majorInitiative:
          type: string
        objectiveId:
          type: integer
        createdBy: 
          type: integer
        status:
          $ref: '#/components/schemas/KrStatus'

